disabled_rules:
 - nesting
 - class_delegate_protocol

opt_in_rules: # some rules are only opt-in
  - empty_count
  - redundant_nil_coalescing
  - switch_case_on_newline
  - force_unwrapping
  - conditional_returns_on_newline
  - closure_spacing
  - sorted_imports
  - valid_docs
  - attributes
  - array
  - yoda_condition

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

force_cast: warning # implicitly

force_try:
  severity: warning # explicitly

identifier_name:
  min_length: 1
  max_length: 50

type_name:
  min_length: 1
  max_length: 50
